name: Deploy to DigitalOcean Droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Cambia a la versión que estés usando

      - name: Install javascript-obfuscator
        run: npm install -g javascript-obfuscator

      - name: Obfuscate code
        run: |
          javascript-obfuscator ./crm-ui-v0.1.js --output ./crm-ui-v0.1-obfuscated.js
          javascript-obfuscator ./v2.js --output ./v2-obfuscated.js

      - name: List generated files
        run: |
          ls -l  # Lista los archivos en el directorio actual

      - name: Show obfuscated file content
        run: |
          echo "Obfuscated crm-ui-v0.1.js:"
          cat ./crm-ui-v0.1-obfuscated.js
          echo "Obfuscated v2.js:"
          cat ./v2-obfuscated.js

      - name: Deploy to DigitalOcean Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/digitaldevops.com.mx/
            cd library-v1
            
           
            echo '------------------------------------'
            echo 'Deployment to Digital Ocean finished'
            echo '------------------------------------'
