name: Deploy to Nginx on Push to Main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Imprimir Secrets
        run: |
          echo "DROPLET_IP:${{ secrets.DROPLET_IP }}"
          echo "DROPLET_USERNAME:${{ secrets.DROPLET_USERNAME }}"
          echo "SSH_PRIVATE_KEY:${{ secrets.SSH_PRIVATE_KEY }}"

      - name: Checkout code
        uses: actions/checkout@v2


      - name: Copy files to Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}



