name: Deploy Library to Droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create exclusion list
        id: exclude
        run: echo "/etc/**/*,/run/**/*" > exclude.txt

      - name: Transfer Library to Droplet
        run: |
          scp -i ${{ secrets.SSH_PRIVATE_KEY }} \
              -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              -r --exclude-from=exclude.txt \
              . ${{ secrets.DROPLET_USERNAME }}@${{ secrets.DROPLET_IP }}:/library/v1
