name: Deploy to Nginx on Push to Main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Imprimir Secrets
        run: |
          echo "DROPLET_IP:${{ vars.DROPLET_IP }}"
          echo "DROPLET_USERNAME:${{ vars.DROPLET_USERNAME }}"
          echo "SSH_PRIVATE_KEY:${{ vars.SSH_PRIVATE_KEY }}"

      - name: Checkout code
        uses: actions/checkout@v2


      - name: Copy files to Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.DROPLET_IP }}
          username: ${{ vars.DROPLET_USERNAME }}
          key: ${{ vars.SSH_PRIVATE_KEY }}
          script: |
            echo "$SSH_PRIVATE_KEY"



