name: remote ssh command
on: [push]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands
        uses: appleboy/ssh-action@v0.1.4
        with:
          script_stop: true
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: whoami

      - name: Imprimir Secrets
        run: |
          echo "DROPLET_IP:${{ secrets.DROPLET_IP }}"
          echo "DROPLET_USERNAME:${{ secrets.DROPLET_USERNAME }}"
          echo "SSH_PRIVATE_KEY:${{ secrets.SSH_PRIVATE_KEY }}"
          echo " ssh -i ${{ secrets.DROPLET_USERNAME }} ${{ secrets.DROPLET_USERNAME }}:${{ secrets.DROPLET_IP }}"
          cd /library
          dir