name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    

    - name: Imprimir Secrets
      run: |
        echo "DROPLET_IP:${{ secrets.DROPLET_IP }}"
        echo "DROPLET_USERNAME:${{ secrets.DROPLET_USERNAME }}"
        echo "SSH_PRIVATE_KEY:${{ secrets.SSH_PRIVATE_KEY }}"
        echo " ssh -i ${{ secrets.DROPLET_USERNAME }} ${{ secrets.DROPLET_USERNAME }}:${{ secrets.DROPLET_IP }}"
        cd /library
        dir