name: Deploy to DigitalOcean Droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2  # Clona el repositorio

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Cambia a la versión que estés usando

      - name: Install javascript-obfuscator
        run: npm install -g javascript-obfuscator

      - name: Obfuscate code
        run: |
          # Asegúrate de que los archivos existan antes de la ofuscación
          echo "Checking for source files:"
          ls -la  # Lista los archivos para confirmar que los scripts originales existen
          javascript-obfuscator ./crm-ui-v0.1.js --output ./crm-ui-v0.1-obfuscated.js
          javascript-obfuscator ./v2.js --output ./v2-obfuscated.js
          
          # Verificar si los archivos ofuscados fueron creados
          echo "Checking for obfuscated files:"
          ls -la  # Lista los archivos en el directorio actual después de la ofuscación

      - name: Deploy to DigitalOcean Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/digitaldevops.com.mx/
            # Elimina los scripts anteriores
            rm -f crm-ui-v0.1.js v2.js  
            # Clona el repositorio para obtener la última versión
            git clone git@github.com:DigitalDevopsMaster/library-v1.git temp-repo
            # Copia el script ofuscado al servidor
            cp temp-repo/crm-ui-v0.1-obfuscated.js ./crm-ui-v0.1.js  
            # Copia el segundo script ofuscado
            cp temp-repo/v2-obfuscated.js ./v2.js  
            # Limpia el directorio temporal
            rm -rf temp-repo
            echo '------------------------------------'
            echo 'Deployment to Digital Ocean finished'
            echo '------------------------------------'
