name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.DROPLET_IP }}
        username: ${{ secrets.DROPLET_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: whoami

    - name: Imprimir Secrets
      run: |
        echo "DROPLET_IP:${{ secrets.DROPLET_IP }}"
        echo "DROPLET_USERNAME:${{ secrets.DROPLET_USERNAME }}"
        echo "SSH_PRIVATE_KEY:${{ secrets.SSH_PRIVATE_KEY }}"
