name: Deploy Library to Droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create exclusion list
        run: echo "/etc/**/*,/run/**/*" > exclude.txt

      - name: Transfer Library to Droplet
        run: |
          cat exclude.txt
          scp -i ${{ secrets.SSH_PRIVATE_KEY }} \
              -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              -r $(grep -v -f exclude.txt <(ls -A)) \
              ${{ secrets.DROPLET_USERNAME }}@${{ secrets.DROPLET_IP }}:/library/v1
