name: Deploy to DigitalOcean Droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Cambia a la versión que estés usando

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build  # O el comando que uses para construir tu proyecto

      - name: Obfuscate code
        run: |
          npx javascript-obfuscator ./dist --output ./dist-obfuscated  # Cambia ./dist según tu estructura de carpetas

      - name: Deploy to DigitalOcean Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/digitaldevops.com.mx/
            rm -rf library-v1
            git clone git@github.com:DigitalDevopsMaster/library-v1.git
            cp -r library-v1/dist-obfuscated/* ./  # Copia los archivos ofuscados
            echo '------------------------------------'
            echo 'Deployment to Digital Ocean finished'
            echo '------------------------------------'
